### ISSUE TITLE
Error on `deno cache ...` and in Deno Deploy

### ISSUE THREAD

**Issue by deanveloper** [discordeno/serverless-deno-deploy-template#17]
```
Error The deployment failed: failed to fetch 'https://raw.githubusercontent.com/usesift/media_types/34656bf398c81f2687fa5010e56844dac4e7a2e9/mod.ts': HTTP status client error (404 Not Found) for url (https://raw.githubusercontent.com/usesift/media_types/34656bf398c81f2687fa5010e56844dac4e7a2e9/mod.ts)
```

**Comment by itohatweb** [comment]
Do you know from where this fetch comes?

**Comment by deanveloper** [comment]
It looks like it's a failed import in sift: https://deno.land/x/sift@0.3.0/mod.ts#L15

**Comment by deanveloper** [comment]
And looks like it's been fixed in 0.4.2: https://deno.land/x/sift@0.4.2/mod.ts#L16

**Comment by itohatweb** [comment]
Looks like the GitHub account of this person got deleted. This issue does not have to do with the templates code directly, it's because of the `sift` module. Please report it to https://github.com/satyarohith/sift

**Comment by deanveloper** [comment]
Can this be reopened? It's already fixed in sift, but the template needs to be updated to use the newer version

**Comment by itohatweb** [comment]
OO, ok lemme update the deps, one min
